apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: road-monitor-ingress
  namespace: road-monitor
  labels:
    app: road-monitor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - goodroad.su
    - api.goodroad.su
    secretName: road-monitor-tls
  rules:
  - host: goodroad.su
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
  - host: api.goodroad.su
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8001